version: "3.8"
services:
  open-blazor-ui:
    container_name: open-blazor-ui
    hostname: open-blazor
    image: obaki102/open-blazor-ui:latest
    ports:
      - "8081:8080"
    environment:
      - OLLAMA_BASE_URL=http://host.docker.internal:11434